### ISSUE TITLE
Searching for a Prefab doesn't always show results starting with Unity.GameObjects

### ISSUE THREAD

**Issue by TimmermanV** [yasirkula/UnityAssetUsageDetector#19]
If I search for a Prefab and have 'Don't search "Find references of" themselves for references' unchecked, the results are not always as clear as I'd expect/hope/like. ;-)

For example, the orange marked object is actually in the scene as well, but doesn't show up as a result itself. (is this as expected?)
![Example](https://user-images.githubusercontent.com/7878208/74102790-2db7c180-4b47-11ea-9a74-1e851802e9ab.png)

However, when switching to "Shorter" view, the result doesn't start with the game object, but shows the prefab itself as the root. (if I click it, the prefab is selected in the project view) I would have expected to see the game object in the scene as first result.
![image](https://user-images.githubusercontent.com/7878208/74102878-cea67c80-4b47-11ea-8875-9b068590bfb2.png)

If I enable  'Don't search "Find references of" themselves for references' the Shorter view does show the game object. However, the other game object that holds an indirect reference is not shown. (is this as expected?)
![image](https://user-images.githubusercontent.com/7878208/74102909-14634500-4b48-11ea-978f-8a038f10235c.png)

So my main issue is that in some cases, neither the Full, nor the Shorter view shows the Prefab instance as a search result.

**Comment by yasirkula** [comment]
Shorter path drawing mode shows only the last few nodes of each path and these paths always start with a UnityEngine.Object. It is the expected behaviour for Shadow to not appear in the last image, it should appear only in Full path drawing mode.

After a search is complete, AssetUsageDetector removes root nodes that are already a part of other nodes' paths, here is the code that does that:

https://github.com/yasirkula/UnityAssetUsageDetector/blob/17d3b33e8e0567e4877cfb2fd004795d4a2073f6/Plugins/AssetUsageDetector/Editor/SearchResult.cs#L517-L522

This reduces the number of duplicate entries in search results. Feel free to uncomment it and see if it helps.

'_Don't search "Find references of" themselves for references_' is set to *true* by default since it can make the search results harder to interpret as you're experiencing. My recommendation is to set it to *false* only if you have multiple objects in "_Find references of_" list and you are interested in the references between these objects, as well.

> neither the Full, nor the Shorter view

Here, you've meant "neither the Shorter, nor the Shortest view", right? Full path should show all references (as seen in the first picture).

**Comment by TimmermanV** [comment]
It was actually about "Splash" not appearing as a search result. "Splash" is an instance of the Prefab I'm searching for, yet I only get indirect references through a different GameObject in the same scene.

**Comment by yasirkula** [comment]
It doesn't appear at the root of the Full view because of the code snippet I've shared, this is the expected behaviour.

You can see Splash at the root in Shorter view when '*Don't search "Find references of" themselves for references*' is set to *true* because this is the Full path when that option is enabled:

![ss](https://user-images.githubusercontent.com/10211608/74107048-4347de00-4b7d-11ea-84fa-17aedcc5bc75.png)

When we follow the path in reverse order, the first UnityEngine.Object we see is Splash GameObject. When '*Don't search "Find references of" themselves for references*' is disabled, the first UnityEngine.Object we see is a NodeCanvas.BehaviourTrees.BehaviourTreeOwner component, hence why it is at the root of the Shorter view in your second screenshot. But as I said, I agree that it'd be better for search results of a scene to always start with a scene object in Shorter view; I'll try to implement this feature and keep this issue open until then.

**Comment by TimmermanV** [comment]
Thanks for the explanation and for considering this feature. :-)
