### ISSUE TITLE
EndLayoutGroup

### ISSUE THREAD

**Issue by puschie286** [yasirkula/UnityAssetUsageDetector#20]
Get an error after search some times. It does not effect the result or the overall functionality ( didnt notice any problems )

Callstack with message:
`EndLayoutGroup: BeginLayoutGroup must be called first.
UnityEditor.EditorGUILayout:EndScrollView()
AssetUsageDetectorNamespace.AssetUsageDetectorWindow:OnGUI() (at Assets/Third Party/AssetUsageDetector/Editor/AssetUsageDetectorWindow.cs:606)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
`

**Comment by yasirkula** [comment]
I couldn't pinpoint this issue since BeginLayoutGroup is present at the very beginning of the same function: https://github.com/yasirkula/UnityAssetUsageDetector/blob/7b939a21047675a8af478e3daf0f68107eb89e64/Plugins/AssetUsageDetector/Editor/AssetUsageDetectorWindow.cs#L352

It's probably a harmless Unity issue.
