### ISSUE TITLE
Possible to use it by code?

### ISSUE THREAD

**Issue by brunomikoski** [yasirkula/UnityAssetUsageDetector#30]
I'm wondering if would be possible to execute the search by code? I have a really specific setup that I would like to know all the references to a lot of assets, ignore some folders and get just a clear list of assets with no reference at all. 

Right now its quite hard to see what has no reference in the result window.

**Comment by yasirkula** [comment]
`SearchResult searchResult = new AssetUsageDetector().Run(...);` will do the job. **SearchResult** isn't documented because there isn't any demand for running Asset Usage Detector programmatically (apart from this Issue 😄) but its public API should be easy to grasp. **SearchResultGroup**s are scenes or Project window and **ReferenceNode**s are nodes under those groups. A ReferenceNode can have links to multiple ReferenceNodes. Traversing ReferenceNodes' links is equivalent to reading the search results from left to right in _Full 'Path drawing mode'_.

**Comment by brunomikoski** [comment]
Thanks for answering so quickly! 
So yeah I kinda tried that path before, but for some reason, I can't get the same results as I would get by the `RightClick/Search for References`.


This is what I'm trying: 
```
List<Object> subAssets = new List<Object>();
for (int i = 0; i < Selection.objects.Length; i++)
    subAssets.AddRange(AssetDatabase.LoadAllAssetsAtPath(AssetDatabase.GetAssetPath(Selection.objects[i])));

AssetUsageDetector.Parameters searchParameters = new AssetUsageDetector.Parameters();
searchParameters.searchInScenes = SceneSearchMode.ScenesInBuildSettingsTickedOnly;
searchParameters.objectsToSearch = Selection.objects;
searchParameters.searchInAssetsSubset = subAssets.ToArray();
SearchResult searchResult = new AssetUsageDetector().Run(searchParameters);
Debug.Log($"Total Result Groups: {searchResult.NumberOfGroups}");
```
This gives me this output:
```
Searched 112 objects in 0.36 seconds
Total Result Groups: 0
```

And by the right-click:
```
Searched 524 objects in 2.39 seconds
```
And I can see 3 results on the window.

Not sure if is some setting I'm missing or something, any idea?

**Comment by yasirkula** [comment]
**searchParameters.searchInAssetsSubset** is the equivalent of "_Search following asset(s) only_". You should pass `subAssets.ToArray()` to searchParameters.objectsToSearch instead.

**Comment by brunomikoski** [comment]
> **searchParameters.searchInAssetsSubset** is the equivalent of "_Search following asset(s) only_". You should pass `subAssets.ToArray()` to searchParameters.objectsToSearch instead.

That was it! Perfect! <3 thanks a lot for the help! And amazing packages! You are awesome!
