### ISSUE TITLE
Nested prefabs are not detected

### ISSUE THREAD

**Issue by Guillaume-Chanko** [yasirkula/UnityAssetUsageDetector#32]
**Description of the bug**

Nested prefabs are not detected.

**Reproduction steps**

Create a prefab A. Then create another prefab B containing an instance of the prefab A. Then look for prefab A with Asset Usage Detector. Scenes containing prefab A will be found, but not prefab B itself or scenes containing prefab B.

**Comment by yasirkula** [comment]
I get this result on 2021.3.13:

![image](https://user-images.githubusercontent.com/10211608/206843228-19479b59-be68-4337-8c44-d36b74f3edaa.png)

I've added B to A instead of A to B but the case is the same. Clicking "B (GameObject) [Prefab object]" line highlights A prefab in Project window and if it's open in Prefab Mode, then it highlights B inside the prefab as seen in screenshot above. B was detected correctly in a Scene, as well.

My settings:

![image](https://user-images.githubusercontent.com/10211608/206843361-a69a3e7e-eb4d-433e-b8c9-9268c84e616c.png)

**Comment by yasirkula** [comment]
Closed due to inactivity.
